# Generated by Django 2.1.3 on 2019-01-06 18:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter House Name', max_length=250)),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('date_created', models.DateTimeField(verbose_name='date created')),
                ('date_updated', models.DateTimeField(verbose_name='date updated')),
            ],
            options={
                'verbose_name': 'house',
                'verbose_name_plural': 'houses',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='HouseInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID field', primary_key=True, serialize=False)),
                ('availability', models.BooleanField(default=False)),
                ('house', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='houses.House')),
            ],
            options={
                'ordering': ['availability'],
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='house',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.Manager', verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='house',
            name='tag',
            field=models.ManyToManyField(blank=True, to='houses.Tag'),
        ),
    ]
