# Generated by Django 2.1.3 on 2019-01-06 20:35

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 1, 6, 20, 34, 46, 730796), verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manager',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manager',
            name='phone',
            field=models.CharField(default='djkfhjdfhjdfh', max_length=20),
            preserve_default=False,
        ),
    ]
